### ISSUE TITLE
Yeees.

### ISSUE THREAD

**Issue by momo5502** [project-bo4/shield-development#1]
![image](https://user-images.githubusercontent.com/4027748/223374896-29d2374b-9287-4f52-bc27-91f2cac3f9b4.png)

Thanks for opensourcing. If you add a little bit of credits, I would be very happy :)
Thank you and good luck with it :D

**Comment by project-bo4** [comment]
s1x project directory is named "**src**", we changed it to "**source**" **:D**

also good luck for you too when treyarch pushes weekly updates(re-compile same stuff) to shift functions alignment :)

Jokes aside thanks for awesome base; as said before we were going to re-write a new one from scratch and still made some remarkable changes; but as you request for immediate consideration of gnu terms we didnt had time to do so.

**Comment by momo5502** [comment]
You can keep the base. I mean if it was bad I wouldn't have written it :P Only a small note in readme would be cool :D

Also, I doubt atvi is gonna push another update 😂

**Comment by project-bo4** [comment]
i didnt mean its bad or un-usable; talking about new one because in case you are not happy with someone using your base. anyways added credit in readme. have nice day

**Comment by momo5502** [comment]
Thank you very much. And rewriting the base is the best possible option to learn from what I did and even improve it :)
