### ISSUE TITLE
crash reports

### ISSUE THREAD

**Issue by Kiaos** [project-bo4/shield-development#12]
I have no idea where to post crashes so I thought id post them here.
[bo4-crash-2023-07-03-18-59-07.zip](https://github.com/project-bo4/shield-development/files/11943323/bo4-crash-2023-07-03-18-59-07.zip)

i was going threw all the calling cards to get rid of the green unseen icon cause im ocd. when going into the tiger cheata section i crashed.

**Comment by project-bo4** [comment]
apparently in this case exception thrown from somewhere outside of game's main module so i cant figure anything out of it. but we are going to add an extended crash dumper in near future to help track and possibly solve respective problems.
