### ISSUE TITLE
Online play

### ISSUE THREAD

**Issue by Abolfazl-Mehrabi** [project-bo4/shield-development#14]
can we play with our friends using virtual lan apps such as radminVPN or Hamachi or ... ?

**Comment by qwertzuiii** [comment]
No, but next is a P2P update. (I have that info from the discord server)

**Comment by project-bo4** [comment]
unfortunately not yet but we are working our best to make it possible. it might take some time before it reaches fully playable state



> No, but next is a P2P update. (I have that info from the discord server)

btw i dont remember ever mentioning something about this

**Comment by qwertzuiii** [comment]
An administrator mentioned it (BodNJenie).

Can't wait for the P2P and Aim Assist Update.

**Comment by bodnjenie14** [comment]
Done - close this issue

**Comment by bodnjenie14** [comment]
Close
