### ISSUE TITLE
[bug] pause menu 

### ISSUE THREAD

**Issue by Koriebonx98** [project-bo4/shield-development#17]
In game especially on zombies, unable to pause game, change class, quit game ect 
Until death or match ends

**Comment by project-bo4** [comment]
if you are using controller and having problem with navigating through menu its normal since pc ports are not very controller friendly on these older cod games. otherwise its not related to this client and theres something wrong with your Mnk and shouldnt be issued here.

**Comment by Koriebonx98** [comment]
It’s the same with mouse and keyboard, pressing the esc button to pause doesn’t work in game. Navigating when the menu is available does work

**Comment by redZONErare** [comment]
> It’s the same with mouse and keyboard, pressing the esc button to pause doesn’t work in game. Navigating when the menu is available does work

You might have faced that one bug that erases all of your keybinds, which I've faced a few times before, though I haven't figured out a way to reproduce it consistently. For now you can try resetting your keybinds back to default if that is the issue you're facing.

**Comment by Koriebonx98** [comment]
> > It’s the same with mouse and keyboard, pressing the esc button to pause doesn’t work in game. Navigating when the menu is available does work
> 
> You might have faced that one bug that erases all of your keybinds, which I've faced a few times before, though I haven't figured out a way to reproduce it consistently. For now you can try resetting your keybinds back to default if that is the issue you're facing.

glad not the only one, I’ll give it a try this week/next week when next load mod. I’ll drop a comment if worked or not

**Comment by Koriebonx98** [comment]
> > It’s the same with mouse and keyboard, pressing the esc button to pause doesn’t work in game. Navigating when the menu is available does work
> 
> You might have faced that one bug that erases all of your keybinds, which I've faced a few times before, though I haven't figured out a way to reproduce it consistently. For now you can try resetting your keybinds back to default if that is the issue you're facing.

can confirm this fixed the issue
