### ISSUE TITLE
LPC Files missing

### ISSUE THREAD

**Issue by ImNickedNPC** [project-bo4/shield-development#21]
Attempted to launch for the first time, and it says I need LPC files not provided by the download

**Comment by Ston3Cold** [comment]
You need to own the game via battle.net in order to download the LPC files via the launcher.

**Comment by ImNickedNPC** [comment]
I do, i just forgot to launch without the client first mb

**Comment by ImNickedNPC** [comment]
I'm stupid i needed to launch the game first then close then relaunch it with the dll, i reformatted so i needed to reinstall the game, im officially retarded
