### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by Koriebonx98** [project-bo4/shield-development#25]
hello is there any docs of the commands that are usable?

**Comment by yousef157** [comment]
https://github.com/project-bo4/shield-development/blob/master/source/proxy-dll/definitions/variables.cpp

**Comment by Koriebonx98** [comment]
Appreciate that, notice there is not a “connect <ipv4> command, has this changed due to newer cod or has it not been added yet? 

Many thanks 
Korie

**Comment by yousef157** [comment]
It has not been added yet.
