### ISSUE TITLE
Connect to p2p

### ISSUE THREAD

**Issue by Koriebonx98** [project-bo4/shield-development#26]
Is there a command like iw4x where you type “connect <ipv4>” but I can’t find it in this one, has ur changed or something?

**Comment by bodnjenie14** [comment]
we dont have one currently
 
u can connect via ip or use launcher

**Comment by bodnjenie14** [comment]
> So I have to change my ip to there’s in order to play together?
> 
> what do you mean by launcher?

https://github.com/bodnjenie14/Project_-bo4_Launcher/tree/main

**Comment by Koriebonx98** [comment]
> > So I have to change my ip to there’s in order to play together?
> > what do you mean by launcher?
> 
> https://github.com/bodnjenie14/Project_-bo4_Launcher/tree/main

Does this have a master server?

move tried to set up and it’s a bit iffy

**Comment by bodnjenie14** [comment]
> > > So I have to change my ip to there’s in order to play together?
> > > what do you mean by launcher?
> > 
> > 
> > https://github.com/bodnjenie14/Project_-bo4_Launcher/tree/main
> 
> Does this have a master server?
> 
> move tried to set up and it’s a bit iffy

https://discord.gg/AXECAzJJGU join here ill help yah

**Comment by Koriebonx98** [comment]
So been tryna use the launcher app, I have found some bugs.

1) when 2x pcs on same connection try to load one goes black screen other connects (using IP’s provided) 

2) using custom ip, same issue

**Comment by bodnjenie14** [comment]
> So been tryna use the launcher app, I have found some bugs.
> 
> 1. when 2x pcs on same connection try to load one goes black screen other connects (using IP’s provided)
> 2. using custom ip, same issue

black screen is known issue with shield not the launcher just litrally keep retrying it


  • I have a black screen when i open the game, how can i fix this ?
  ◦ Go in the root folder of your game and delete BlackOps4.start.
  ◦ If it didn’t work delete BlackOps4.start and open the game with admin rights.
  ◦ If this did not work delete BlackOps4.start and restart your pc.

**Comment by Koriebonx98** [comment]
Okay I’ll give this a try tomorrow, the black screen doesn’t tend to happen if you play it on one pc, but if it’s 2 connected to the same lan switch then one will start and the other won’t 👀

**Comment by bodnjenie14** [comment]
> Okay I’ll give this a try tomorrow, the black screen doesn’t tend to happen if you play it on one pc, but if it’s 2 connected to the same lan switch then one will start and the other won’t 👀

Also check you both haven’t got the same xuid in your project-bo4.json (can be found in game folder) 

You will both only have the same xuid if you used the same battlenet account to download the game on both PC’s or simply copied the folder from one pc to another.

If u both do have the same xuid . Simply change one number in one of them and save it.

You can not join the lobby’s with the same xuid the game thinks your the same person

**Comment by Koriebonx98** [comment]
> > Okay I’ll give this a try tomorrow, the black screen doesn’t tend to happen if you play it on one pc, but if it’s 2 connected to the same lan switch then one will start and the other won’t 👀
> 
> Also check you both haven’t got the same xuid in your project-bo4.json (can be found in game folder)
> 
> You will both only have the same xuid if you used the same battlenet account to download the game on both PC’s or simply copied the folder from one pc to another.
> 
> If u both do have the same xuid . Simply change one number in one of them and save it.
> 
> You can not join the lobby’s with the same xuid the game thinks your the same person

That’s the thing, I’ve deleted the .json file as well as the players folder to fully reset and still same situation.

I have made that mistake in past with Iw6-mod where I didn’t clear the player folder so they wouldn’t connect until I changed.

but as of now, same issue occurs, if you could try see if you can replicate it, if not might just be a me problem.

idealy need 2x systems on same network.

and with the IP’s isn’t one for local host? Or is self hosting not possible? As I do like to play with bots as they lag less, and helpful when connections not good or lack of players

**Comment by bodnjenie14** [comment]
> > > Okay I’ll give this a try tomorrow, the black screen doesn’t tend to happen if you play it on one pc, but if it’s 2 connected to the same lan switch then one will start and the other won’t 👀
> > 
> > 
> > Also check you both haven’t got the same xuid in your project-bo4.json (can be found in game folder)
> > You will both only have the same xuid if you used the same battlenet account to download the game on both PC’s or simply copied the folder from one pc to another.
> > If u both do have the same xuid . Simply change one number in one of them and save it.
> > You can not join the lobby’s with the same xuid the game thinks your the same person
> 
> That’s the thing, I’ve deleted the .json file as well as the players folder to fully reset and still same situation.
> 
> I have made that mistake in past with Iw6-mod where I didn’t clear the player folder so they wouldn’t connect until I changed.
> 
> but as of now, same issue occurs, if you could try see if you can replicate it, if not might just be a me problem.
> 
> idealy need 2x systems on same network.
> 
> and with the IP’s isn’t one for local host? Or is self hosting not possible? As I do like to play with bots as they lag less, and helpful when connections not good or lack of players

https://discord.gg/AXECAzJJGU

join discord and message me (bodnjenie) ill get ths sorted with you once and for all 

deleteting the json will still recrate the json with identical "xuid" numbers .. You will need to edit them like i said 

I have multiple pc's on my network and the only reason they wont connect with each other is the same "xuid"

**Comment by bodnjenie14** [comment]
Close
