### ISSUE TITLE
[DEMONWARE] Issue with people cloning wrong branch

### ISSUE THREAD

**Issue by jumofogit** [project-bo4/shield-development#3]
![Снимок экрана (3)](https://user-images.githubusercontent.com/116519368/227208352-65d365fc-421b-4fea-af7e-6c2fa7d80e37.png)

**Comment by project-bo4** [comment]
greetings. firstly by the looks of status label apparently you retrieved master branch of git; in case of getting and building demonware branch you will have '**CONNECTED**' message down there.

Also this applies for everyone else; plz before taking screenshot hit INS button on keyboard for extended debug info which provides a clue for developers to understand what problem could possibly be and help you with it.

Have nice day :)

**Comment by jumofogit** [comment]
![image](https://user-images.githubusercontent.com/116519368/227400346-e951ffa7-8ede-451e-ac42-7b0f3ab322dd.png)
[project-bo4.log](https://github.com/project-bo4/shield-development/files/11057638/project-bo4.log)
still can't connect

**Comment by project-bo4** [comment]
Yes as i told before, you have cloned main branch. also within readme we emphasized you to double check everything before submitting issue. Also You didnt check readme nor read answer we provided. **This is not OK**


You have simply entered this cmd in git or powershell: `git clone https://github.com/project-bo4/shield-development.git`
meanwhile you need to enter this to get dw branch: `git clone --branch demonware --single-branch https://github.com/project-bo4/shield-development.git`


Simple google search of '**How to clone specific branch in git**' would have get your answer.

**Comment by jumofogit** [comment]
well. I saw another one problem. progression in Zombies working, but not.

**Comment by project-bo4** [comment]
Please add detailed information; we dont work with riddles here.

Also reminder this is a very early stage of project being still being worked on. There havent been anything even close to what we got here since call of duty moved on to battle.net®. You cannot expect flawless functionality until final public release.

**Comment by project-bo4** [comment]
we are aware of stats issue and investigating it. 
I close this thread as solved.
