### ISSUE TITLE
Error when playing Alpha Omega

### ISSUE THREAD

**Issue by PotatoMiner34290** [project-bo4/shield-development#35]
an error occurred: Zulu 523 Lion
just goes back to action report from prevous match/lobby
![zulu](https://github.com/project-bo4/shield-development/assets/157565681/43cc9902-cce6-4520-8759-fd4d001249bd)

**Comment by ate47** [comment]
This is not a problem with the client, this probably linked with a mod you installed. Uninstall it and it should be fine.

**Comment by bodnjenie14** [comment]
Close
