### ISSUE TITLE
[Bug] Crashes when trying to launch in Parallels on an Apple Silicon Mac

### ISSUE THREAD

**Issue by nickoanastassiu** [project-bo4/shield-development#37]
Since the official game doesn't launch in any way shape or form on macOS, I decided "what have I to lose?" so I tried this. Launching at least showed the ( ͡° ͜ʖ ͡°) boot view, then it errors and says "check minidump".

### System Info
**CPU** - M2 Pro (8 cores allocated to Windows, 4 to macOS)
**Memory** - 16GB (10GB allocated to Windows, 6 to macOS)
**Host OS Version** - macOS Sonoma 14.4 beta 3
**VM OS Version** - Windows 11 Pro ARM (Insider Build 26052)

### Minidump File
[shield-crash-2024-03-07-22-40-38.zip](https://github.com/project-bo4/shield-development/files/14529888/shield-crash-2024-03-07-22-40-38.zip)

**Comment by project-bo4** [comment]
hey sorry for the late answer. actually the dump that has been generated has empty stack and doesnt provide any information

any idea the architecture you mentioned is base ARM or ARM64?

**Comment by nickoanastassiu** [comment]
Should be ARM64. Windows reports it as such.
![CleanShot 2024-08-16 at 21 47 07@2x](https://github.com/user-attachments/assets/110487f8-f41d-40b5-a3f1-1a1718a99842)

**Comment by project-bo4** [comment]
anyways there are no useful information recorded in the dump other than crash happening in one of auxiliary threads and not main trunk. it could even be something other than game engine like dlls from operating system running a code that conflicts process. I doubt if there is anything I could do but if you really want it message me on discord(project_bo4) and I will have to set interceptors and try my luck with attempting to make it work.

**Comment by nickoanastassiu** [comment]
Alright, I might DM you this week if I find the time. Thanks.
