### ISSUE TITLE
Please switch to using minhook lib instead of dll

### ISSUE THREAD

**Issue by maiyuzhe** [project-bo4/shield-development#49]
Would simplify things a bit and then only require d3d11.dll

**Comment by ate47** [comment]
(It's already the case: [minhook.lua](https://github.com/project-bo4/shield-development/blob/master/deps/premake/minhook.lua))

**Comment by project-bo4** [comment]
wdym? none of deps are dynamically linked; Also I dont believe minhook having any exports to be a dll.
