### ISSUE TITLE
Linux/SteamOS support?

### ISSUE THREAD

**Issue by ComoSgt** [project-bo4/shield-development#5]
I wanted to ask if there would be support for the Steam Deck. The game runs perfectly so I was curious if this future modification would be supported on the platform as well or if testing is needed, I can help out through that.

**Comment by project-bo4** [comment]
coincidently today someone in our discord did ask about it and I took his log file and after inspecting it I found everything had functioned fine other than Live service wasn't getting pumped after certain point (he was using wine with ubuntu)

we will look after it soon.

**Comment by ComoSgt** [comment]
I've been testing and I can agree, everything works perfectly besides the one issue everyone seems to have in which you can't level up in zombies despite it showing as such in-game. The only issue I have when playing on the Deck is that whenever I close the game by exiting out via the in-game option, it'll give me a debug error saying that "abort() has been called"
