### ISSUE TITLE
What does this mean

### ISSUE THREAD

**Issue by LARELLPYTHON** [project-bo4/shield-development#52]
![image_2024-09-13_000438885](https://github.com/user-attachments/assets/b6aaceb8-30da-4bec-b90f-f824bd0ac4ce)

**Comment by project-bo4** [comment]
you have 2 different iterations of our proxydlls. probably one leftover from before which will be d3d11.dll. delete it and it will be fine.

**Comment by Pyro16** [comment]
I got the same error and I deleted d3d11.dll but still my game is not starting. Once i clicked on BlackOps4.exe below screen appears. 

![BlackOps4Error1](https://github.com/user-attachments/assets/2a006bf6-ecef-4f7f-8d87-849aea1373df)

I also tried to run Start BO4 (English).exe couple of time. I got below screen for CMD followed by black screen and them game exist.

![BlackOps4Error2](https://github.com/user-attachments/assets/d1a63a6a-2d26-4a34-bc7a-19cc17db1bf8)

Attached minidump files for reference.
[shield-crash-2024-09-18-15-31-51.zip](https://github.com/user-attachments/files/17042264/shield-crash-2024-09-18-15-31-51.zip)
[shield-crash-2024-09-18-15-32-34.zip](https://github.com/user-attachments/files/17042266/shield-crash-2024-09-18-15-32-34.zip)
[shield-crash-2024-09-18-15-34-07.zip](https://github.com/user-attachments/files/17042267/shield-crash-2024-09-18-15-34-07.zip)

My First challenge which i face is to start offline (campaign) game.
