### ISSUE TITLE
Can't level up in zombies

### ISSUE THREAD

**Issue by Robinmist88** [project-bo4/shield-development#53]
![bo41](https://github.com/user-attachments/assets/9e4704db-2222-4e0e-9668-905af7a691d6)
![bo42](https://github.com/user-attachments/assets/82a03d4c-1024-4c3f-a4b3-ac0de78c6cb3)

Even though I'm level 29, it says I'm level 1 and I can't use any unlocks. Does anyone have a fix for this?

**Comment by project-bo4** [comment]
Added the solution to public repo: 
https://github.com/project-bo4/shield-development/commit/00082c2001b66760b8847139fa5df250f1fc54cf
