### ISSUE TITLE
Leveling

### ISSUE THREAD

**Issue by zrx499** [project-bo4/shield-development#9]
I have a problem where in the lobby my level is 1 and ingame it shows im 55, and it does not unlock for me the weapons and everything in lobby.

**Comment by Ston3Cold** [comment]
Highly doubt unlocking any items/weapons work currently in the client. You'll need to wait for it be properly implemented. I think what you're seeing is most likely just a glitch at this stage.

**Comment by bodnjenie14** [comment]
Unlock all done - close this

**Comment by bodnjenie14** [comment]
Close
